version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: ecommerce-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ecommerce-net

  app:
    build: .
    container_name: ecommerce-api
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - ecommerce-net

volumes:
  db_data:

networks:
  ecommerce-net:
